create table if not exists public.garden_notes (
  id bigint generated by default as identity primary key,
  body text not null check (char_length(trim(body)) > 0),
  created_at timestamptz not null default now()
);

alter table public.garden_notes enable row level security;

create policy "Anyone can read garden notes"
  on public.garden_notes
  for select
  to anon, authenticated
  using (true);

create policy "Anyone can create garden notes"
  on public.garden_notes
  for insert
  to anon, authenticated
  with check (true);
