create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  email_notifications_enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  text text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_assignments (
  user_id uuid not null references public.profiles(id) on delete cascade,
  date date not null,
  challenge_id bigint not null references public.challenges(id),
  created_at timestamptz not null default now(),
  primary key (user_id, date)
);

create table if not exists public.checkins (
  user_id uuid not null references public.profiles(id) on delete cascade,
  date date not null,
  completed boolean not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, date)
);

create table if not exists public.email_notifications (
  token text primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  date date not null,
  challenge_id bigint not null references public.challenges(id),
  sent_at timestamptz,
  completed_at timestamptz,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (user_id, date)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_checkins_updated_at on public.checkins;
create trigger set_checkins_updated_at
  before update on public.checkins
  for each row
  execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, coalesce(new.email, ''))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

insert into public.challenges (text, active)
values
  ('Bring a hot drink to someone you care about.', true),
  ('Send a short message to a person you have lost touch with.', true),
  ('Hold the door open for the next stranger you meet.', true),
  ('Leave a small thank-you note where someone will find it.', true),
  ('Pay full attention to one person speaking to you today.', true),
  ('Offer a sincere compliment without expecting a reply.', true),
  ('Help carry something for someone who has their hands full.', true),
  ('Cook or share a small meal with someone in your home.', true),
  ('Call a family member just to ask how they are.', true),
  ('Give up your seat or your spot in line.', true),
  ('Listen to someone''s story without offering advice.', true),
  ('Make space for someone to merge in front of you while driving.', true),
  ('Tidy a shared space without telling anyone you did.', true),
  ('Write down three things you appreciate about a person you know.', true),
  ('Bring something small from outside, like a flower or leaf, to someone indoors.', true),
  ('Ask someone how they are really doing, and wait for the real answer.', true),
  ('Forgive a small thing today, quietly, in your own mind.', true),
  ('Help a neighbour with something they did not ask for.', true),
  ('Put your phone away for an entire meal with another person.', true),
  ('Send a photo of something beautiful to someone you love.', true),
  ('Thank someone who serves you by name, slowly.', true),
  ('Pick up one piece of litter that is not yours.', true),
  ('Offer to take a photo for a stranger or family.', true),
  ('Reach out to someone who recently went through something hard.', true),
  ('Make eye contact and smile at three people today.', true),
  ('Let someone else choose first today: what to watch, where to eat, or where to go.', true),
  ('Share a memory with someone who was part of it.', true),
  ('Leave a generous tip without making it a moment.', true),
  ('Sit with someone in silence for a minute, on purpose.', true),
  ('Tell someone what they mean to you directly, in plain words.', true)
on conflict (text) do nothing;

alter table public.profiles enable row level security;
alter table public.challenges enable row level security;
alter table public.daily_assignments enable row level security;
alter table public.checkins enable row level security;
alter table public.email_notifications enable row level security;

drop policy if exists "Profiles are visible to owners" on public.profiles;
create policy "Profiles are visible to owners"
  on public.profiles
  for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "Profiles are editable by owners" on public.profiles;
create policy "Profiles are editable by owners"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Profiles are created by owners" on public.profiles;
create policy "Profiles are created by owners"
  on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "Challenges are readable by signed in users" on public.challenges;
create policy "Challenges are readable by signed in users"
  on public.challenges
  for select
  to authenticated
  using (active = true);

drop policy if exists "Assignments are visible to owners" on public.daily_assignments;
create policy "Assignments are visible to owners"
  on public.daily_assignments
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Assignments are created by owners" on public.daily_assignments;
create policy "Assignments are created by owners"
  on public.daily_assignments
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Checkins are visible to owners" on public.checkins;
create policy "Checkins are visible to owners"
  on public.checkins
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Checkins are created by owners" on public.checkins;
create policy "Checkins are created by owners"
  on public.checkins
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Checkins are updated by owners" on public.checkins;
create policy "Checkins are updated by owners"
  on public.checkins
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Notifications are visible to owners" on public.email_notifications;
create policy "Notifications are visible to owners"
  on public.email_notifications
  for select
  to authenticated
  using (auth.uid() = user_id);
